app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[
    path('', views.home, name='home'), 
    path('register/', views.create_user, name='register'), 
    path('login/', views.login_user, name='login'),
    path('candidate/', views.candidate, name='candidate'),
    path('position/', views.positionView, name='position'),
    path('candidate/<int:pos>/', views.candidateView, name='candidatelist'),
    path('candidate/detail/<int:id>/', views.candidate_delete, name='detail'),
    path('result/', views.resultView, name='result'),

]
if settings.DEBUG:

    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

    

]

app/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
import secrets
from cloudinary.models import CloudinaryField
class Position(models.Model):
    title = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.title


class Candidate(models.Model):
    name = models.CharField(max_length=50)
    total_vote = models.IntegerField(default=0, editable=False)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    image=CloudinaryField('image')
    def __str__(self):
        return "{} - {}".format(self.name, self.position.title)


class Votes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    time_voted=models.DateTimeField()

    def __str__(self):
        return "{} - {} - {}".format(self.user, self.position, self.status)

# POSITIONS = (
#         ("President", "President"),
#         ("Vice-President", "Vice-President"),
#         ("Secretary-General", "Secretary-General"),
#     )

# class Candidate(models.Model):
#     name=models.CharField(max_length=255)
#     image=CloudinaryField('image')
#     position=models.CharField(max_length=50,choices=POSITIONS)
#     admin = models.ForeignKey(User, on_delete=models.CASCADE)

#     def user_can_vote(self, user):
#         """ 
#         Return False if user already voted
#         """
#         user_votes = user.vote_set.all()
#         qs = user_votes.filter(poll=self)
#         if qs.exists():
#             return False
#         return True

#     @property
#     def get_vote_count(self):
#         return self.vote_set.count()

#     def get_result_dict(self):
#         res = []
#         for choice in self.choice_set.all():
#             d = {}
           
#             d['num_votes'] = choice.get_vote_count
#             if not self.get_vote_count:
#                 d['percentage'] = 0
#             else:
#                 d['percentage'] = (choice.get_vote_count /
#                                    self.get_vote_count)*100

#             res.append(d)
#         return res

#     def __str__(self):
#         return self.text


# class Votes(models.Model):
#     voter_name=models.OneToOneField(User, on_delete=models.CASCADE)
#     time_voted=models.DateTimeField()
#     candidate_voted = models.ForeignKey(Candidate,on_delete=models.CASCADE)
    

#     def __str__(self):
#         return f'{self.poll.text[:15]} - {self.choice.choice_text[:15]} - {self.user.username}'

app/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
    
    
    
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
 

    
</head>

<body>
    {% include "navbar.html" %}
    <div class="container mt-3">
        {% block content %}

        {% endblock %}
       
    </div>
    {% include "footer.html" %}
    <!-- scripts -->
    {% block scripts %}
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
   
    {% bootstrap_javascript %}
    {% endblock %}
</body>

</html>

app/templates/candidate_list.html
{% extends "base.html" %}

{% block title %}Candidate{% endblock %}

{% block content %}

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <h2>Available Candidates of {{ obj.title }}</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% for c in obj.candidate_set.all %}
      <!-- <input type="radio" name="{{ c.position}}" value="{{c.id}}" required> <strong>{{c.name}} <a href="{% url 'detail' c.id %}">Detail</a></strong>
     <br> -->
     <div class="custom-control custom-radio">
      <input type="radio" id="id_{{c.id}}" name="{{ c.position}}" value="{{c.id}}" class="custom-control-input" required>
      <label class="custom-control-label" for="id_{{c.id}}">{{c.name}} <a href="{% url 'detail' c.id %}">Detail</a></label>
    </div>
    {% empty %}
      <p>No Candidates Available</p>
    {% endfor %}
    <br><input type="submit" class="btn btn-outline-success btn-sm" value="VOTE">
  </form>
  <br><p><a href="{% url 'position' %}">Back to Poll</a></p>
{% endblock %}

app/templates/candidates.html
{%extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <div class="container" style="margin-top: 2%;">
    <button class="btn btn-outline-dark btn-sm" id="site" data-toggle="modal" data-target="#candidateModal">
        POST A CANDIDATE
    </button>
    <br>
		<div class="row">
			{% for candidate in candidates %}
			<div class="col-lg-4">
				<img class="thumbnail" src="{{candidate.image.url}}" class="img-respnsive" width="100%" height="300px">
				<div class="box-element product">
					<h6 class="text-center"><strong>{{candidate.name}}</strong></h6>
					<hr>
	
					
					
					
					<h4 style="display: inline-block;"><strong> {{candidate.position}}</strong></h4>
                    <i class="fa fa-trash-o" aria-hidden="true">Delete candidate</i>
				</div>
                
			</div>
			{% endfor %}
		</div>

	
        <div class="modal fade" tabindex="-1" id="candidateModal" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Post a Candidate</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        </div>
        
	
{% endblock content %}

app/templates/footer.html
{% load bootstrap4 %}

{% load static %}

{% block content %}
<footer class="site-footer" style="margin-bottom: 300px; background-color: #83b71d;">
    <div class="container" >
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-5">
              <h2 class="footer-heading mb-4">About Us</h2>
              <p>Dedan Kimathi University of Technology (DeKUT) is a Chartered Public University that has two campuses: the Main Campus in Nyeri and Nairobi Campus along Loita street. </p>
            </div>
            <div class="col-md-3 mx-auto">
              <h2 class="footer-heading mb-4">Contacts</h2>
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Testimonials</a></li>
                <li><a href="#">Contact Us</a></li>
              </ul>
            </div>
            
          </div>
        </div>
        <div class="col-md-4">
          <div class="mb-4">
            <h2 class="footer-heading mb-4">Subscribe Newsletter</h2>
          <form action="" method="post" class="footer-subscribe">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input type="email" name="email" class="form-control border-secondary text-white bg-transparent" required placeholder="Enter Email" aria-label="Enter Email" aria-describedby="button-addon2">
              <div class="input-group-append">
                <button class="btn btn-dark text-black" type="submit" id="button-addon2">Send</button>
              </div>
            </div>
          </form> 

         
          </div>
          
          <div class="">
            <h2 class="footer-heading mb-4">Follow Us</h2>
              <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
          </div>


        </div>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-12">
        <div class="border-top" style="margin-top:120px;">
        <p class="copyright pt-4"><small>&copy; <script>document.write(new Date().getFullYear());</script> Dkut. All Rights Reserved By.<a href="/" target="_blank">Dkut.com</a></small></p>
        </div>
      </div>
      
    </div>
  </footer>

  <a href="#top" style="border-radius: 80px;background-color: darkcyan;" class="gototop"><span class="icon-angle-double-up"></span></a>

 {%endblock%}

app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- homepage section -->

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p style="margin-left: 70%;">ARE YOU A MEMBER? <a href="login/">LOGIN</a></p>
                </div>
            </div>
            <div class="row">
               
                <div class="col-md-12 text-center" id ="homepage">
                    <button type="button" style="background-color: transparent;" class="btn btn-warning">GET STARTED <i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                </div>
               
        </div>
        </div>
    

{% endblock %}

app/templates/positions.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
  <h2>Available Position For Vote</h2>
  <ul>
    {% for i in obj %}
      <li><a href="{% url 'candidate' i.id %}">{{i.title}}</a></li>
    {% empty %}
      <p>No Positions Available</p>
    {% endfor %}
  </ul>
{% endblock %}

app/templates/results.html
{% extends "base.html" %}

{% block title %}Result Page{% endblock %}

{% block content %}
  <h2 class="text-center">Result</h2>
  <table class="table table-bordered table-sm text-center">
    <thead>
      <tr>
        <th>Candidate Name</th>
        <th>Candidate Position</th>
        <th>Total Vote</th>
      </tr>
    </thead>
    <tbody>
      {% for i in obj %}
        <tr>
          <td>{{ i.name }}</td>
          <td>{{ i.position }}</td>
          <td>{{ i.total_vote }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}